# Generated by Django 2.2.2 on 2019-06-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='quote',
            field=models.IntegerField(null=True, verbose_name='引用ID'),
        ),
    ]
